---
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1003
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - /home/aleixmt/sonarr:/config
      - /srv/sambashare/BIG_BIG_DATA1/:/tv  # optional
      - /srv/sambashare/BIG_DATA/sonarr-downloads:/downloads  # optional
    ports:
      - 8989:8989
    restart: unless-stopped
