---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1003
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - /home/aleixmt/radarr:/config
      - /srv/sambashare/BIG_BIG_DATA1/disk/_Pelis:/movies #optional
      - /srv/sambashare/BIG_BIG_DATA1/disk/_Torrent-transmission:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
