{
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=132  # Sambashare user GID
      - TZ=Europe/London
    volumes:
      - /home/aleixmt/bazarr:/config
      - /srv/sambashare/BIG_BIG_DATA1/disk/_Pelis:/movies  # Optional
      - /srv/sambashare/BIG_BIG_DATA1/disk/:/tv  # Optional
    ports:
      - 6767:6767
    restart: unless-stopped
}
