version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=132  # Sambashare user GID
      - TZ=Europe/London
    volumes:
      - /home/aleixmt/Bazarr/config:/config
      - /samba/media/disk/_Pelis:/samba/media/disk/_Pelis  # Optional
      - /samba/media/disk/_Series:/samba/media/disk/_Series  # Optional
    ports:
      - 6767:6767
    restart: unless-stopped
